update changelog, build files for 2022.03
NOAA-GFDL/FMS pull request #1012
Opened 2022-07-28 15:52 UTC by rem1776

**Description**
release changes

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2022-07-28 15:58 UTC, bensonr requested changes

2022-07-28 15:58 UTC, bensonr commented on CHANGELOG.md
> +- Current diag_manager does not add "tileX" to the filename when using a cube sphere, which leads to trouble when trying to combine the files and regrid them (if the region is in two different tiles)
This needs to call out more clearly that this case only occurs when outputting sub-region diagnostics

2022-07-28 16:36 UTC, bensonr approved these changes

2022-07-29 16:14 UTC, thomas-robinson approved these changes

2022-07-29 16:19 UTC, merged