Closes issue #1051
NOAA-GFDL/FMS pull request #1061
Opened 2022-10-24 21:30 UTC by nikizadehgfdl

- This fixes compile issue with nvhpc/22.5 on t5

**Description**
Pass the length of input string that is declared as class(*)

Fixes #1051 

**How Has This Been Tested?**
Only compilation is tested. Needs to be regression tested.

**Checklist:**
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2022-10-25 12:13 UTC, thomas-robinson approved these changes

2022-10-25 12:14 UTC, thomas-robinson requested changes
@nikizadehgfdl Your lines are too long.  That's why they failed the linter.  I think you should use some line continuations for the strings you are passing in.

2022-10-26 14:26 UTC, rem1776 approved these changes

2022-10-26 14:49 UTC, thomas-robinson approved these changes

2022-10-26 15:05 UTC, merged