Completed #ifdef use_deprecated_io
NOAA-GFDL/FMS pull request #1064
Opened 2022-11-02 18:19 UTC by mcallic2

**Description**
Adds `#ifdef use_depreciated_io` around all fms_io modules and any calls included in old io 

Fixes # (issue)

**How Has This Been Tested?**
Tested with autotools on the sky box with oneapi

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2022-11-03 13:50 UTC, rem1776 requested changes
I left some comments, but I think this will need some other changes as well cause the data override test is failing in the ci.

2022-11-03 13:50 UTC, rem1776 commented on test_fms/parser/parser_demo.F90
> +#ifdef use_deprecated_io
this one shouldn't be ifdef'd, doesn't use any old io.

2022-11-03 21:41 UTC, uramirez8707 requested changes
I don't see the `#ifdef use_deprecated_io ` around mpp/mpp_io.F90

2022-11-09 19:28 UTC, rem1776 requested changes

2022-11-09 19:28 UTC, rem1776 commented on test_fms/mpp/test_mpp_gatscat.F90
> +  use mpp_io_mod, only: mpp_flush
you can delete this use and any calls to mpp flush if there is any

2022-11-09 19:28 UTC, rem1776 commented on test_fms/mpp/test_mpp_sendrecv.F90
> +  use mpp_io_mod, only: mpp_flush
same as last comment

2023-02-09 18:49 UTC, uramirez8707 commented on axis_utils/axis_utils.F90
> +#ifdef use_deprecated_io
I think it should be empty, the code will not compile if someone tries to use any of the `axis_utils_mod`

2023-02-09 18:55 UTC, uramirez8707 commented
The coupler CI is failing because `ocean_null` has not been updated to use fms2_io
```
ocean_null/ocean_model.F90:26:28:

   26 | use           fms_mod, only: field_size, field_exist, get_mosaic_tile_grid, set_domain
      |                            1
Error: Symbol 'field_size' referenced at (1) not found in module 'fms_mod'

```

I updated `ocean_null` a long time ago, but never got into the main repo
https://github.com/NOAA-GFDL/ocean_null/pull/4

2023-03-31 16:14 UTC, thomas-robinson commented
@uramirez8707 and @mcallic2 What is being done for fixing the failed coupler compile build test?  Do we know when we can update it so that the build works?

2023-03-31 16:20 UTC, uramirez8707 commented
I think @nikizadehgfdl needs to merge 
https://github.com/NOAA-GFDL/ocean_null/pull/4 And then re run the CI

2023-04-19 19:46 UTC, rem1776 commented on test_fms/mpp/test_mpp_gatscat.F90
> +  use mpp_io_mod, only: mpp_flush
@mcallic2 could you remove these `mpp_flush` statements for this and the other test? I don't think they are even used and it'd be better to not use the old io at all in unrelated tests

2023-04-24 18:38 UTC, rem1776 commented on mpp/mpp_io.F90
> -  public :: mpp_io_init, mpp_io_exit, netcdf_err, mpp_flush, mpp_get_maxunits, do_cf_compliance
can you add this back? still needs to be there so its public for other components

2023-04-24 19:17 UTC, rem1776 submitted a review, later dismissed

2023-06-30 16:39 UTC, rem1776 approved these changes

2023-06-30 16:52 UTC, thomas-robinson approved these changes

2023-06-30 16:53 UTC, thomas-robinson commented
@mcallic2 This needs an issue linked to it

2023-06-30 18:22 UTC, merged