Change fortran header file extenstions from .h to .fh
NOAA-GFDL/FMS pull request #1087
Opened 2022-12-07 23:32 UTC by mcallic2

**Description**
This changes the extension names from .h to .fh for fortran header files within FMS. It also changes any calls to the header files.

Fixes # (issue)

**How Has This Been Tested?**
Testes with autotools using oneapi and cmake
@rem1776 @underwoo 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2022-12-14 20:38 UTC, rem1776 requested changes
just needs the doxygen fix i left the comment about in a few spots

2022-12-14 20:38 UTC, rem1776 commented on constants/geos_constants.fh
> +real(kind=RKIND), public, parameter :: RADCON     = ((1.0E+02*GRAV)/(1.0D+04*CP_AIR))*SECONDS_PER_DAY
The `!<` was moved to the next line but it needs to be on the same line as the variable its describing for it to get read by doxygen correctly.

If its close to the length limit you can start it with nothing, it'll still read the other lines:
```
real(kind=RKIND), public, parameter :: RADCON     = ((1.0E+02*GRAV)/(1.0D+04*CP_AIR))*SECONDS_PER_DAY !<
                                                                              !! rest of
                                                                              !! the comment
```

2022-12-19 16:40 UTC, rem1776 approved these changes

2022-12-20 12:56 UTC, thomas-robinson commented
@mcallic2 You need to link an issue for this.

2022-12-23 15:32 UTC, thomas-robinson approved these changes

2022-12-23 15:41 UTC, merged