Mixed precision astronomy
NOAA-GFDL/FMS pull request #1092
Opened 2022-12-16 19:08 UTC by mcallic2

**Description**
Changes to add mixed precision to astronomy files

Fixes # (issue)

**How Has This Been Tested?**
Autotools using oneapi and cmake

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2023-05-31 13:19 UTC, mlee03 requested changes

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    where(t >= PI) t = real(t, FMS_AST_KIND_) - real(twopi, FMS_AST_KIND_)
t is already in FMS_AST_KIND_

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    t = gmt + lon - PI
real(PI,FMS_AST_KIND_)

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +            cosz = real(aa, FMS_AST_KIND_) + real(bb, FMS_AST_KIND_)&
why all the real(,FMS_AST_KIND_) here?

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +                                           fracday = real(fracday, FMS_AST_KIND_) + &
here too, fracday does not need real(,FMS_AST_KIND_)

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +      h_out    = h/PI
real(PI,FMS_AST_KIND_)

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +          t     = real(float(n-1), FMS_AST_KIND_)*real(twopi, FMS_AST_KIND_)/real(float(num_angles), FMS_AST_KIND_)
don't need the float here

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +        solar   = solar/float(num_angles)
real(num_angles,FMS_AST_KIND_)

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    norm_time = real(t, FMS_AST_KIND_)*real(float(num_angles), FMS_AST_KIND_)/real(twopi, FMS_AST_KIND_)
don't need float here

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    ANGLE_    = (1.0_lkind - real(x, FMS_AST_KIND_))*real(orb_angle(int), FMS_AST_KIND_) &
x is already in FMS_AST_KIND_

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    ANGLE_    = modulo(real(ANGLE_, FMS_AST_KIND_), real(twopi, FMS_AST_KIND_))
ANGLE_ is already in FMS_AST_KIND_

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +real(kind=FMS_AST_KIND_) :: eps = real(1.0E-05, FMS_AST_KIND_) !< small increment
1.0E-5_lkind

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    where (latitude == -0.5_lkind*PI) lat = latitude + eps
real(PI,FMS_AST_KIND_)

2023-05-31 13:19 UTC, mlee03 commented on astronomy/include/astronomy.inc
> +    where (cos_half_day <= -1.0_lkind) h = PI
real(PI,FMS_AST_KIND_)

2023-05-31 13:21 UTC, mlee03 commented on astronomy/astronomy.F90
> +
Should there be more interfaces for all the subroutines and functions in astronomy.inc?

2023-06-02 17:32 UTC, mcallic2 commented on astronomy/astronomy.F90
> +dt = twopi/float(num_angles)
resolved in 9e832558

2023-06-02 17:36 UTC, mcallic2 commented on astronomy/astronomy.F90
> +dt = twopi/float(num_angles)
resolved in 9e832558abec513634a54b05e2d114b93414ccad

2023-07-26 13:37 UTC, mlee03 commented
@mcallic2 , could you add @J-Lentz as a reviewer

2023-07-26 13:49 UTC, mlee03 reviewed
@mcallic2 make sure to compile with  -Wall -Wconversion-extra for GCC to catch all the kind/type mismatch

2023-07-26 13:49 UTC, mlee03 commented on test_fms/astronomy/test_daily_mean.F90
> +    do i = 1, 4
could use n instead of 4

2023-07-26 13:49 UTC, mlee03 commented on test_fms/astronomy/test_annual_mean_solar_1d.F90
> +      if (abs(ref_cosz(i) - cosz(i)) .gt. real(1E-07,TEST_AST_KIND_)) then
1.e-7_lkind

2023-08-02 15:37 UTC, mlee03 commented on astronomy/astronomy.F90
> +    period_out = int(real(seconds_per_day, r8_kind)*days + seconds)
real(days,r8_kind), real(seconds,r8_kind)

2023-08-02 15:39 UTC, mlee03 requested changes

2023-08-02 15:39 UTC, mlee03 commented on astronomy/astronomy.F90
> +            period = int(real(seconds_per_day, r8_kind)*days + seconds)
real(days,r8_kind), real(seconds,r8_kind)

2023-08-02 15:39 UTC, mlee03 commented on astronomy/astronomy.F90
> +
is_valid=.false.

2023-08-02 15:39 UTC, mlee03 commented on astronomy/astronomy.F90
> +          jd = size(latb,2) - 1
if(is_valid) then 
 id = size(lonb,1) - 1
            allocate (cosz_ann(id, jd))
            allocate (solar_ann(id, jd))
            allocate (fracday_ann(id, jd))
            total_pts = jd*id
end if

2023-08-02 15:41 UTC, mlee03 commented on test_fms/astronomy/test_astronomy.F90
> +
can you add more comments?

2023-08-14 19:49 UTC, mlee03 commented on astronomy/astronomy.F90
> +            period = int(real(seconds_per_day, r8_kind)*days + seconds)
missed this one?

2023-08-14 19:49 UTC, mlee03 commented on astronomy/astronomy.F90
> +    twopi = 2.0_r8_kind * real(PI, r8_kind)
don't need the real() for PI here

2023-08-16 17:22 UTC, mlee03 commented on astronomy/astronomy.F90
> +          jd = size(latb,2) - 1
you need a if(is_valid) statement here

2023-08-18 14:43 UTC, mlee03 approved these changes

2023-08-18 18:27 UTC, rem1776 approved these changes

2023-08-18 18:28 UTC, merged

2023-08-22 19:15 UTC, mlee03 commented on astronomy/astronomy.F90
> +    t = twopi*(t - real(t, r8_kind))
@mcallic2 , was this originally a floor?

2023-08-22 19:16 UTC, mlee03 commented on astronomy/astronomy.F90
> +    t = twopi*(t - real(t, r8_kind))
I think it should have been real(floor(t),r8_kind)