Port to Intel LLVM based compilers
NOAA-GFDL/FMS pull request #1098
Opened 2022-12-28 16:17 UTC by dkokron

The Intel LLVM based compilers don't support certain flags.  In particular, -no-prec-div -no-prec-sqrt and -fp-model source
See https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html for details.

Add logic to cmake/compiler_flags_Intel_*.cmake to handle this.

Tested on an Ubuntu-22.04 system using the 2023.0.0. release of oneAPI.

2022-12-29 19:10 UTC, thomas-robinson commented
@aerorahul can you please review this?  You are the original author of this code.

2022-12-29 19:11 UTC, thomas-robinson commented
@dkokron I'm not sure why you skipped the template for the PR, but can you open an issue and link that issue to this PR.  Then you will have to check the boxes indicating you are aware of and followed the guidelines for contributing.

2022-12-29 19:35 UTC, aerorahul requested changes
1. `IntelLLVM` is a valid `CMAKE_<LANG>_COMPILER_ID` and instead of placing `if-elseif` logic in `compiler_flags_Intel_<LANG>.cmake`, please consider adding new files specific to IntelLLVM e.g. `compiler_flags_IntelLLVM_C.cmake` etc.
2. The top-level `CMakeLists.txt` will need an update; specifically lines 44 and 49 to allow support for `IntelLLVM` compiler family.  E.g.
```
if(NOT CMAKE_C_COMPILER_ID MATCHES "^(Intel|IntelLLVM|GNU|Clang)$")
``` 
and 
```
if(NOT CMAKE_Fortran_COMPILER_ID MATCHES "^(Intel|IntelLLVM|GNU)$")
```
respectively
3. The file `cmake/fms_compiler_flags.cmake` should be updated to extend support to `IntelLLVM` e.g.
```
elseif(CMAKE_Fortran_COMPILER_ID MATCHES "IntelLLVM")
  include(compiler_flags_IntelLLVM_Fortran)
```
and similar for the `C` compiler.

I understand there is quite a bit of repetition between the `Intel` and `IntelLLVM` compiler flags. 
My recommendation is to keep them separate so it is absolutely clear which family is used and what those flags are.

Other than that, there are a few `WARNING` messages being placed that don't need to be and could use some attention.

Out of curiosity, I noticed `-fp-model source` is being omitted from `IntelLLVM`.  Otherwise they are identical.  Can you explain why that is the case?

If they end up being identical, we can come up with a different logic than separate files for `Intel` and `IntelLLVM`.

2022-12-29 19:35 UTC, aerorahul commented on cmake/compiler_flags_Intel_C.cmake
> +if(CMAKE_C_COMPILER_ID STREQUAL "Intel")
This file is for providing flags for the `Intel` `C` compiler.
Please create a file `compiler_flags_IntelLLVM_C.cmake` for the `IntelLLVM` `C` family.

2022-12-29 19:35 UTC, aerorahul commented on cmake/compiler_flags_Intel_Fortran.cmake
> +if(CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
This file is for providing flags for the `Intel` `Fortran` compiler.
Please create a file `compiler_flags_IntelLLVM_Fortran.cmake` for the `IntelLLVM` `F` family.

2022-12-29 21:28 UTC, aerorahul submitted a review, later dismissed
Changes look good to me.  Thank you for incorporating the suggestions.

2022-12-29 22:39 UTC, dkokron commented
I have updated the CMake files as requested.  Please review and let me know if there are any other changes needed.

2022-12-29 22:43 UTC, dkokron commented
As to why I removed "fp-model source", the source option is no longer supported by the LLVM based compilers.  See https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/floating-point-options/fp-model-fp.html

2022-12-29 22:49 UTC, aerorahul commented
> As to why I removed "fp-model source", the source option is no longer supported by the LLVM based compilers. See https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/floating-point-options/fp-model-fp.html

I couldn't find any explicit reference to LLVM, but that is ok since we have separate files for the LLVM compiler ID.

2022-12-29 22:49 UTC, aerorahul approved these changes
Changes look good.

2023-01-09 13:53 UTC, rem1776 approved these changes

2023-01-09 19:41 UTC, merged