Time io update
NOAA-GFDL/FMS pull request #1129
Opened 2023-02-01 21:13 UTC by uramirez8707

**Description**
This PR:
 1.  Update to write out the time data based on how FMS was compiled to reproduce previous diag manager behavior
 2.  Implement capability to specify which time in a time average period to use when setting filename and adds tests for it

Fixes # (issue)

**How Has This Been Tested?**
CI, including updated tests

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2023-02-14 13:46 UTC, thomas-robinson requested changes
At a minimum, you need to add 4 spaces to the end of the "double    " string when you set it.  I think you should also add the namelist flag for reproducing the old behavior.

2023-02-15 19:03 UTC, uramirez8707 commented on diag_manager/diag_data.F90
> +  CHARACTER(len=10) :: pack_size_str="double" !< Pack size as a string to be used in fms2_io register call
why?

2023-02-15 19:04 UTC, uramirez8707 commented on diag_manager/diag_data.F90
> +  !! This is to reproduce previous diag manager behavior.
what is the new behavior?

2023-02-15 19:06 UTC, uramirez8707 commented on diag_manager/fms_diag_yaml.F90
> +  deallocate(buffer)
The buffer always gets allocated in `diag_get_value_from_key`, there is no need to check

2023-02-15 20:06 UTC, thomas-robinson commented on diag_manager/diag_data.F90
> +  CHARACTER(len=10) :: pack_size_str="double" !< Pack size as a string to be used in fms2_io register call
Some compilers require this when setting a variable.

2023-02-15 20:06 UTC, thomas-robinson commented on diag_manager/diag_data.F90
> +  !! This is to reproduce previous diag manager behavior.
we should discuss this more

2023-02-21 18:58 UTC, uramirez8707 commented on diag_manager/diag_data.F90
> +  CHARACTER(len=10) :: pack_size_str="double" !< Pack size as a string to be used in fms2_io register call
https://github.com/NOAA-GFDL/FMS/pull/1129/commits/3ac08c6eca17f8d1c85c55818d7237983fd22427

2023-02-22 19:06 UTC, merged