Documentation update to dmUpdate branch
NOAA-GFDL/FMS pull request #1161
Opened 2023-03-20 17:57 UTC by ganganoaa

**Description**
Include a new file, docs_uml/MDMClassObjects.drawio, which contains class and object diagrams based on the modern diag manager concept.

Fixes # (issue)

**How Has This Been Tested?**
N/A

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2023-03-22 17:20 UTC, thomas-robinson requested changes
Redo this PR so it just has the documentation update changes.

2023-03-22 20:07 UTC, ganganoaa commented
requested changes updated.

2023-03-28 12:30 UTC, rem1776 approved these changes

2023-04-25 16:54 UTC, thomas-robinson approved these changes

2023-04-25 16:55 UTC, merged