add missed alias in libfms.F90
NOAA-GFDL/FMS pull request #1303
Opened 2023-07-26 20:16 UTC by rem1776

**Description**
adds 2 missed aliases in libFMS.F90 that slipped through with the last update.

Fixes #1288  (thanks Lauren for spotting these!)

**How Has This Been Tested?**
CI

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2023-07-27 11:04 UTC, thomas-robinson requested changes
This needs an update in the coupler

2023-07-27 11:17 UTC, laurenchilutti commented
> This needs an update in the coupler

And also atmos_drivers

2025-05-13 16:47 UTC, uramirez8707 approved these changes

2025-05-13 19:24 UTC, bensonr approved these changes

2025-05-14 11:30 UTC, thomas-robinson approved these changes

2025-05-14 14:12 UTC, merged