Add tile number to the filename for subregional files
NOAA-GFDL/FMS pull request #1376
Opened 2023-09-22 18:12 UTC by uramirez8707

**Description**
Add tile number to the filename for subregional files

Fixes #1008 

**How Has This Been Tested?**
This was tested with an AM4.2 amip run
and this table:
```
ESM4_amip_D1_am4p2_proto7b_isop_whiteCapsAlbedo_salt_nudge_ch4_2d_adj_vmr_high_terpene_SIS2
1870 1 1 0 0 0

"US_aircraft",1,"hours",1,"days","time"
"dynamics", "H2", "H2", "US_aircraft", "all", .true., "232.50,292.50,25.00,50.00,239.00,1000.00", 2
```

Before this update tile was not added to the filename and now it is. This update is needed in order for the combiner to work correctly.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2023-09-22 18:14 UTC, uramirez8707 commented
@rem1776 @thomas-robinson can this be included in the 2023.03?
This came up in helpdesk ticket #5023155

2023-09-27 18:51 UTC, thomas-robinson requested changes

2023-09-27 18:51 UTC, thomas-robinson commented on diag_manager/diag_output.F90
> +    character(len=128) :: tmp_filename      !< Temp variable to store the file_name
What makes this a temporary variable?  It looks like a file name for a specific type of file.

2023-09-27 18:51 UTC, thomas-robinson commented on diag_manager/diag_output.F90
> +    character(len=128) :: tmp_filename      !< Temp variable to store the file_name
The PR description does a better job of describing this variable than either its name or the description here.

2023-10-03 10:42 UTC, thomas-robinson approved these changes

2023-10-05 13:08 UTC, merged