dmUpdate: add diurnal reduction
NOAA-GFDL/FMS pull request #1438
Opened 2024-01-11 16:50 UTC by rem1776

**Description**
draft for now, running into memory issues when running reductions that aren't diurnal. Seems to overwrite the field objects during the reduction assignments.

Fixes # (issue)

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2024-01-17 19:52 UTC, uramirez8707 approved these changes

2024-01-17 19:52 UTC, uramirez8707 commented on diag_manager/fms_diag_object.F90
> + logical :: is_diurnal
It looks like this variable is not actually used/needed?

2024-01-17 19:52 UTC, uramirez8707 commented on test_fms/diag_manager/test_time_diurnal.sh
> +printf "&test_diag_diurnal_nml \n test_case=1 \n / \n" >> input.nml
I think you need to set `OMP_NUM_THREADS` to 2 here

2024-01-18 18:00 UTC, thomas-robinson requested changes
Please make sure all of the variables have descriptive documentation

2024-01-18 18:00 UTC, thomas-robinson commented on diag_manager/include/fms_diag_reduction_methods.inc
> +  integer :: diurnal
needs documentation

2024-01-18 18:49 UTC, thomas-robinson approved these changes

2024-01-18 19:54 UTC, merged