moden diag manager: documentation
NOAA-GFDL/FMS pull request #1483
Opened 2024-03-25 21:39 UTC by uramirez8707

**Description**
Add documentation describing the differences between the old and new diag manager and renames the diag yaml documentation

Fixes # (issue)

**How Has This Been Tested?**
N/A

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-03-26 17:45 UTC, thomas-robinson requested changes

2024-03-26 17:45 UTC, thomas-robinson commented on diag_manager/README.md
> +### 7. Answers "changes"
These are history file differences, not answer changes.

2024-03-26 21:39 UTC, ceblanton approved these changes

2024-03-28 11:18 UTC, thomas-robinson approved these changes

2024-03-28 13:24 UTC, merged