dmUpdate:: Final Fixes
NOAA-GFDL/FMS pull request #1487
Opened 2024-04-09 20:46 UTC by uramirez8707

**Description**
- Keep track of time at a file_level instead of a diag_object level.
- Keep track of the unlimited dimension at a buffer level (this is to ensure that files that have buffers that send data at different frequencies work correctly)

Fixes # (issue)

**How Has This Been Tested?**
CI
SPEAR + MOM/SIS updates

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-04-10 12:15 UTC, thomas-robinson requested changes

2024-04-10 12:15 UTC, thomas-robinson commented on diag_manager/fms_diag_output_buffer.F90
> +end subroutine
Can you add the name of the subroutine here for readability purposes

2024-04-11 11:46 UTC, thomas-robinson approved these changes

2024-04-11 11:46 UTC, thomas-robinson commented
Can you update the name of this PR because it is not descriptive of what it does.

2024-04-16 19:19 UTC, rem1776 approved these changes

2024-04-16 19:20 UTC, merged