2024.01 changelog and version updates
NOAA-GFDL/FMS pull request #1507
Opened 2024-05-02 22:03 UTC by rem1776

**Description**
2024.01 updates

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-05-02 22:08 UTC, uramirez8707 commented on CHANGELOG.md
> +		- The `_FillValue` and `missing_value` attributes will not be added for `average_T1`, `average_T2`, and `average_DT` variables
This should actually say that the average_* variable will no longer be added as they are non-standard conventions.

2024-05-03 12:20 UTC, bensonr commented on CHANGELOG.md
> +	- The `flush_nc_files` and `mix_snapshot_average_fields` nml options are not yet functional. The `mix_snapshot_average_fields` option is planned will to be deprecated (for the rewritten diag_manager
Simple typo here of "is planned will to be"

2024-05-03 14:44 UTC, rem1776 commented
@bensonr @uramirez8707 This should be ready now, it's been updated for those two comments

2024-05-03 15:21 UTC, uramirez8707 approved these changes

2024-05-03 17:25 UTC, bensonr approved these changes

2024-05-03 17:25 UTC, bensonr commented on CHANGELOG.md
> +- DATA_OVERRIDE: Adds multifile support for using 3 input netcdf files instead of one. Three keys have been added to the data_table: `is_multi_file` to be set to true to enable the feature, as well a
The multi-file support in data_override is only up to 3 files?

2024-05-03 17:25 UTC, bensonr commented on CHANGELOG.md
> +- DATA_OVERRIDE: Adds support for monotonically increasing/decreasing arrays
I think this needs clarified for which axes we are able to do this for or at a minimum a reference to the GitHub issue and/or PR.

2024-05-03 18:06 UTC, merged

2024-05-03 18:10 UTC, thomas-robinson requested changes

2024-05-03 18:10 UTC, thomas-robinson commented on CHANGELOG.md
> +  - More flexibility when adding metadata and defining output frequency
- Updated math and buffer handling for better support when send_data is called in a threaded region 
- New diag manager requires a call to diag send complete.  
- @uramirez8707 Do you think there's anything else to add?

2024-05-03 18:10 UTC, thomas-robinson commented on CHANGELOG.md
> +	- Self-describing YAML formatting for diag_table's
You dont need the apostrophe in diag_tables