Data override: ext weights #1521
NOAA-GFDL/FMS pull request #1534
Opened 2024-05-22 19:54 UTC by abrooks1085

**Description**
Subroutine to read new data table yaml format has been updated. Data override test scripts have been updated for new yaml format as well as the data override documentation.

**How Has This Been Tested?**
built on amd box using autotools with gcc/13.2.0, netcdf/4.9.2, mpich/4.1.2, libyaml/0.2.5

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-05-22 20:40 UTC, bensonr requested changes

2024-05-22 20:40 UTC, bensonr commented on data_override/README.MD
> +- `ICE` corresponds to the grid_name in the data_table
I think it's the component domain for which the variable is being interpolated

2024-05-22 20:40 UTC, bensonr commented on data_override/README.MD
>  - `icec` is the variable to write the data to
Isn't that the storage array that holds the interpolated data?

2024-05-22 20:40 UTC, bensonr commented on data_override/README.MD
>  - `Spec_Time` is the time to interpolate the data to.
See comments above.

2024-05-22 20:40 UTC, bensonr commented on data_override/README.MD
>  - `Spec_Time` is the time to interpolate the data to.
See comments above

2024-06-24 17:44 UTC, uramirez8707 requested changes
Just some minor changes.

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +
You should move the call that gets the `factor` here

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +         mentries = get_num_blocks(file_id, "override_file", parent_block_id=entry_id(i))
I think you should add something like

```F90
! initialize the data_override type
data_table(i)%file_name = ""
data_table(i)%fieldname_file = ""
data_table(i)%interpol_method = "none"
data_table(i)%multifile = .false.
data_table(i)%ext_weights = .false.
data_table(i)%region_type = NO_REGION

! If there is no override_file block, then not overriding from file, so move on to the next entry
if (mentries .eq. 0) cycle
```

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +              & is_optional=.true.)
is_optional should be removed now, because you are overriding from a file so the file_name is required

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +              & is_optional=.true.)
is_optional should be removed now, because you are overriding from a file so the fieldname_in_file is required

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +         mentries = get_num_blocks(file_id, "override_file", parent_block_id=entry_id(i))
and remove in the lines below

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/include/data_override.inc
> +              & is_optional=.true.)
is_optional should be removed now, because you are overriding from a file so the interpol_method is required

2024-06-24 17:44 UTC, uramirez8707 commented on data_override/README.MD
> +  - **multi_file:** The multifile parent key. **Required** only if it is desired to use multiple(3) input netcdf files instead of 1. Note that **file_name** must be the second file in the set when us
Can you add an example using that uses multi_file and external_weights?

2024-07-23 19:39 UTC, rem1776 commented
closing since these commits will be included in the PR above

2024-07-23 19:39 UTC, closed without merging