set is_allocated in all horiz_interp_type_new routines
NOAA-GFDL/FMS pull request #1538
Opened 2024-06-03 13:53 UTC by rem1776

**Description**
Sets the `is_allocated` field as well as the `method_type` within horiz_interp_types when called from any of the method specific horiz_interp_new routines. This should prevent reallocation errors as described in the issue below.

Also adds some calls to the unit test to test this functionality.

Fixes #1533

**How Has This Been Tested?**
make distcheck with oneapi 2024.01 on amd box

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-06-24 15:54 UTC, thomas-robinson requested changes

2024-06-24 15:54 UTC, thomas-robinson commented on test_fms/horiz_interp/test_horiz_interp.F90
> +        real(HI_TEST_KIND_), allocatable :: lon_dst_1d(:), lat_dst_1d(:)
These should have doxygen documentation instead of just a comment above

2024-06-27 18:03 UTC, rem1776 commented
@thomas-robinson @bensonr This should be ready now, I updated the SPHERICA to SPHERICAL. I noticed that the interpolation method values were made public in the libFMS.F90 file so I also removed them from there as well since they should only be internal.

2024-06-27 19:33 UTC, bensonr approved these changes

2024-06-28 14:16 UTC, thomas-robinson approved these changes

2024-06-28 14:33 UTC, merged