Modern diag_manager: Simplify the diag table yaml
NOAA-GFDL/FMS pull request #1545
Opened 2024-06-12 15:31 UTC by uramirez8707

**Description**
This simplifies the diag table yaml by allowing the `module`, `reduction` and `kind`  to be set at a file level, with the ability to override them at a field level. 

This is backwards compatible as the old diag table yaml formats should still work. 

Fixes # (issue)

**How Has This Been Tested?**
CI, including added test

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-07-26 12:24 UTC, thomas-robinson commented
Is there an update to the schema?

2024-07-26 12:27 UTC, thomas-robinson requested changes

2024-07-26 12:27 UTC, thomas-robinson commented on diag_manager/diag_yaml_format.md
> +- **module** is a string that defines the module where the variable is registered in the model code
Can this be overwritten on the variable level?  It should be mentioned here.

2024-07-30 14:25 UTC, uramirez8707 commented
> Is there an update to the schema?

@thomas-robinson  https://github.com/NOAA-GFDL/gfdl_msd_schemas/pull/3

2024-08-01 11:04 UTC, thomas-robinson approved these changes

2024-08-01 14:19 UTC, merged