Yaml tables for ensembles and nests
NOAA-GFDL/FMS pull request #1585
Opened 2024-09-04 17:13 UTC by uramirez8707

**Description**
Adds the ability for each ensemble/nest to have its own diag/field/data yaml tables.

This will allow users to specify a unique forcing file for each ensemble member  (Fixes #1568) and to specify a different file frequency for multiple grids (Fixes #1573)

For example, for a run with 2 ensemble members, fms will search for diag_table_ens_01.yaml and diag_table_ens_02.yaml. 
Similarly, for a run with a nest, fms will search for diag_table.yaml (for the parent grid) and diag_table_nest_01.yaml (for the nest grid), `nest_01` can be whatever is passed in to fms via the `set_filename_appendix` call.

Fixes # (issue)

**How Has This Been Tested?**
CI including new tests

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2024-09-06 14:12 UTC, bensonr requested changes

2024-09-06 14:12 UTC, bensonr commented on data_override/include/data_override.inc
> +    character(len=255) :: filename !< Name of the expected data_table.yaml
This should use the filename length macro in platform.F90

2024-09-06 14:12 UTC, bensonr commented on data_override/include/data_override.inc
> +
Need to make it clear in any documentation we are only testing for collisions with `ens_xx` and a generic data_table.yaml and not for `nest_xx` as well.

2024-09-06 14:12 UTC, bensonr commented on diag_manager/fms_diag_yaml.F90
> +  character(len=255)   :: yamlfilename     !< Name of the expected diag_table.yaml
This should use the filename length macro in platform.F90

2024-09-06 14:12 UTC, bensonr commented on diag_manager/fms_diag_yaml.F90
> +  diag_yaml_id = open_and_parse_file(trim(yamlfilename))
Need to make it clear in any documentation we are only testing for collisions with ens_xx and a generic data_table.yaml and not for nest_xx as well.

2024-09-06 14:12 UTC, bensonr commented on field_manager/field_manager.F90
> +
filename macro

2024-09-06 14:12 UTC, bensonr commented on field_manager/field_manager.F90
> +if (.not. file_exists(trim(filename))) then
Same message about checking only `ens_xx`

2024-09-18 20:38 UTC, uramirez8707 commented
@bensonr I think I addressed all your comments in https://github.com/NOAA-GFDL/FMS/pull/1585/commits/1b2e050c9096eb3399996f8c276f45011385ac24

2024-09-19 03:09 UTC, bensonr submitted a review, later dismissed
Thanks for making the changes.

2024-10-24 15:01 UTC, rem1776 approved these changes

2024-10-24 15:04 UTC, merged