Doxygen updates + fixes for building
NOAA-GFDL/FMS pull request #631
Opened 2020-12-04 18:21 UTC by rem1776

**Description**
Makes some adjustments to how autotools builds the docs to fix some issues, in addition to the documentation updates already added in #625 (had to make a second PR because i couldn't edit it directly)

Fixes #

**How Has This Been Tested?**
../configure --enable-docs && make -C docs
 
**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2020-12-04 23:13 UTC, underwoo commented
@rem1776 there appear to be merge conflicts in the PR. Please resolve and push an update.

2020-12-09 19:14 UTC, rem1776 commented
this is ready for review, any merge conflicts were resolved with d80edbb and c903988

2020-12-09 19:42 UTC, thomas-robinson commented
I think we need #331 before we can merge this

2020-12-09 20:51 UTC, wrongkindofdoctor submitted a review, later dismissed

2020-12-21 15:16 UTC, wrongkindofdoctor submitted a review, later dismissed

2021-01-07 16:33 UTC, bensonr approved these changes

2021-01-07 16:35 UTC, bensonr commented
@rem1776 - were any of the mpp/ source files updated from the current HTML style to doxygen?  If not, is doxygen properly configured to parse the HTML when run?

2021-01-07 20:28 UTC, rem1776 commented
@bensonr It looks like Colin didn't update the mpp files so they're still in html. 

It doesn't seem like doxygen can parse the html as is, so I think in order to get the mpp documentation included it'll need to be updated so the documentation is within doxygen comment blocks.

2021-01-07 20:39 UTC, bensonr commented
@rem1776 - it looks like there is some support for parsing html embedded as
documentation  https://www.doxygen.nl/manual/htmlcmds.html.  There might be
a config option to parse the inline html in mpp.

2021-01-07 21:19 UTC, underwoo commented
From testing I did years ago, the HTML documentation is parsable by Doxygen, but the comment tags (`!`) need to be modified to what doxygen is expecting (`![<>!]`).  

It is also important to know that Doxygen **will not** parse comments within the body of a subroutine.  It only parses comments before the subroutine and at the head (right after the beginning of the routine and the input parameters).

2021-01-12 19:03 UTC, thomas-robinson requested changes
Please address the 4 comments

2021-01-12 19:29 UTC, rem1776 commented on diag_manager/diag_axis.F90
> +  !! @return Returns index in axis set table corresponding to a given axis set name
Every function at least has a brief description so should i delete all of the old html style comments then as well?

2021-01-12 19:34 UTC, thomas-robinson commented on diag_manager/diag_axis.F90
> +  !! @return Returns index in axis set table corresponding to a given axis set name
If the comments are covered by doxygen, then there's no need for the double documentation.  It needs to be cleaned up eventually.

2021-01-12 20:28 UTC, rem1776 commented on diag_manager/diag_output.F90
> +                                          !! 8 =  8bit
Replaced this with a table in 48d7e50

2021-01-12 20:29 UTC, rem1776 commented on diag_manager/diag_axis.F90
> +  !! @return Returns index in axis set table corresponding to a given axis set name
I cleaned up the redundant html comments with 48d7e50

2021-01-12 20:31 UTC, rem1776 commented on diag_manager/diag_axis.F90
> +  !> @return Integer length
Fixed wording in 48d7e50

2021-01-12 21:28 UTC, thomas-robinson approved these changes

2021-01-13 18:14 UTC, bensonr approved these changes

2021-01-13 18:29 UTC, merged

2021-01-13 20:07 UTC, wrongkindofdoctor approved these changes