Move write_version_number() from fms_io_mod to fms_mod
NOAA-GFDL/FMS pull request #735
Opened 2021-04-27 19:25 UTC by rem1776

**Description**
Moves the write_version_number routine from fms_io_mod to fms_mod and adds it to libFMS.F90. The routine seems to be always imported via fms_mod so this shouldn't affect other imports.

Since fms_io_mod can't access write_version_number from fms_mod, I moved the write_version_number call from fms_io_init() to fms_init() similar to how the constants_mod version number is written in fms_init(). 

This means the version number for fms_io_mod won't be written on calls to fms_io_init(), but will be written as long as either fms_init() or write_version_number() are called at any point.

Fixes #546 (looks like the other two routines don't need to be moved)

**How Has This Been Tested?**
make check with intel and netcdf 4.6.1 on amd

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2021-04-28 12:32 UTC, bensonr approved these changes

2021-04-28 12:46 UTC, wrongkindofdoctor submitted a review, later dismissed

2021-04-28 15:24 UTC, bensonr requested changes
When we publicize 'version' from libFMS.F90, it should probably be exported as version_FMS by default and not a generic 'version'.

2021-04-28 18:04 UTC, rem1776 commented
@bensonr name should be fixed now, also changed it to get it from file_version.h like any other module (before i think it was included as part of constants_mod)

2021-04-29 18:37 UTC, bensonr submitted a review, later dismissed

2021-04-29 18:53 UTC, rem1776 commented
@bensonr Sorry, needed to change the filename to lowercase to pass CI

2021-04-29 19:00 UTC, bensonr approved these changes

2021-04-29 19:02 UTC, wrongkindofdoctor approved these changes

2021-04-29 19:54 UTC, wrongkindofdoctor approved these changes

2021-04-29 20:12 UTC, bensonr approved these changes

2021-04-29 20:15 UTC, merged