Makes MAX_FIELDS_PER_FILE a namelist variable and allocates
NOAA-GFDL/FMS pull request #750
Opened 2021-05-20 13:06 UTC by thomas-robinson

**Description**
Changes the `max_fields_per_file` to a namelist variable, and allocated the `fields` with this value.

Fixes #747 

**How Has This Been Tested?**
`make` run with intel

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2021-05-20 13:07 UTC, thomas-robinson commented
@menzel-gfdl can you test this?  Does it fulfill your request?

2022-01-20 14:53 UTC, thomas-robinson commented
@menzel-gfdl do you still want this?

2022-01-20 15:02 UTC, bensonr requested changes
If this change goes through, the error message in diag_manager/diag_util.F90  at line 1356ff needs to be updated.

2022-01-20 15:09 UTC, menzel-gfdl commented
@thomas-robinson sorry I've been distracted by a lot of other projects.  What are your thoughts?  I proposed this because we kind of need 5d diagnostics (time, z, lat, lon, spectral dimension).  Right now our only option is to create one variable per spectral dimension (band, wavenumber, gpoint, etc.), which as you can imagine leads to a very high number of diagnostics.  Is there a better solution?

2022-01-20 15:38 UTC, thomas-robinson commented
@menzel-gfdl Yes there is a plan to support more dimensions in the diag manager rewrite.  Although the target is September, there is no guarantee that 5D support will be working by then.  If this PR solves your problem more immediately, then why not take it now.  I don't think there is a reason why this shouldn't be done.

2024-12-18 21:54 UTC, rem1776 commented
closing since the rewritten diag manager does not have this limitation.

2024-12-18 21:54 UTC, closed without merging